---
- name: Install unzip
  apt: name=unzip update_cache=yes

- name: Download consul-template
  unarchive:
    src: https://releases.hashicorp.com/consul-template/0.19.4/consul-template_0.19.4_linux_amd64.zip
    remote_src: yes
    dest: /usr/local/bin

- name: Create directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ consul_template.dir }}"

- name: Copy templates
  copy: src={{ item.src }} dest={{ consul_template.dir }}/{{ item.src }}
  with_items: "{{ consul_template.templates }}"

- name: Copy systemd template
  template: src=consul-template.service.j2 dest=/etc/systemd/system/consul-template.service

- name: Enable service
  service: name=consul-template enabled=yes
