---
- name: Install nginx
  apt: name=nginx state=present

- name: Remove default sites
  file: path={{ item }} state=absent
  with_items:
    - /etc/nginx/conf.d/default.conf
    - /etc/nginx/sites-enabled/default
  notify: restart nginx
  tags:
    - nginx-config

- name: Upload sites
  template:
    src: sites/{{ item }}.conf.j2
    dest: /etc/nginx/conf.d/{{ item }}.conf
  with_items: "{{ nginx.sites }}"
  notify: restart nginx
  tags:
    - nginx-config

- name: Start and enable nginx service
  service: name=nginx state=started enabled=yes
  when: nginx.systemd
